spin_version = "1"
description = "Basic Spin application in Docker"
name = "spin-in-K8S"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "demo-wasm-spin"
source = "WasmContainer.wasm"

[component.trigger]
route = "/..."
executor = { type = "wagi" }