apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-in-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-in-k8s
  template:
    metadata:
      labels:
        app: spin-in-k8s
    spec:
      runtimeClassName: wasmtime-spin-v1
      containers:
        - name: spin-in-k8s
          image: eelcowasmacr.azurecr.io/spin-in-k8s:latest
          imagePullPolicy: "Always"
          command: ["/"]